<?php
// $Id$

/** 
* Implements hook_help()
 */
function youth_training_content_help($path, $arg) {
  $output = '';
  switch($path) {
    case 'admin/help#youth_training_content':
      $output = '<p>' . t('Creates a Quicktabs block programmatically for the All Youth Training Content panel.') . '</p>';
      break;
  }
  return $output;
}

/**
 * Implements hook_menu().
 */
function youth_training_content_menu() {
  $items = array();

  $items['youth'] = array(
	  'title' => 'Urban Ministry Training Library',
    'page callback' => 'youth_training_content_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ); 
  return $items;
}

/**
 * Page callback for /youth-training-content.
 * Shows all youth training content (in Quicktabs).
 */
function youth_training_content_page() {
  return theme('quicktabs', youth_training_content_quicktabs());
}

/**
 * Implements hook_block().
 */
function youth_training_content_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks['ytc_uywi'] = array(
      'info' => t('Youth Training Content: UYWI'),
      'weight' => 0, 
      'status' => 0, 
      'cache' => BLOCK_NO_CACHE,
    );
    $blocks['ytc_ccda'] = array(
      'info' => t('Youth Training Content: CCDA'),
      'weight' => 0, 
      'status' => 0, 
      'cache' => BLOCK_NO_CACHE,
    );
    return $blocks;
  }
  elseif ($op == 'view') {
    switch($delta) {
      case 'ytc_uywi':
        $block = array(
         'content' => youth_training_content_uywi(),
        );
        break;
      case 'ytc_ccda':
        $block = array(
         'content' => youth_training_content_ccda(),
        );
        break;
    }
    return $block;
  }
}

/**
 * Quicktabs block for the /youth-training-content page.
 * Returns a quicktabs array with all youth training content.
 */
function youth_training_content_quicktabs() {
  // Initialize an empty tabs array for the Quicktabs.
  $tabs = array();
	// Add the UYWI tab.
  // This, and the other tabs must be defined as custom blocks or else they could not use AJAX.
  $tabs[] = array(
    'bid' => 'youth_training_content_delta_ytc_uywi',
    'hide_title' => TRUE,
    'title' => 'UYWI',
    'weight' => -80,
    'type' => 'block',
  );
  // Add the CCDA tab.
  $tabs[] = array(
    'bid' => 'youth_training_content_delta_ytc_ccda',
    'hide_title' => TRUE,
    'title' => 'CCDA',
    'weight' => -60,
    'type' => 'block',
  );
  // Add the FASTEN tab.
  $tabs[] = array(
    'nid' => 9767,
    'title' => 'FASTEN',
    'weight' => -100,
    'type' => 'node',
  );
  // Add the Urban Youth Ministry Encyclopedia tab.
  $tabs[] = array(
    'qtid' => 10,
    'title' => 'Youth Encyclopedia',
    'weight' => -20,
    'type' => 'qtabs',
  );
  // Add the TechMission Corps wiki tab.
  $tabs[] = array(
    'nid' => 1046,
    'title' => 'TechMission Corps Wiki',
    'weight' => -40,
    'type' => 'node',
  );
  $quicktabs['qtid'] = 'youthtrainingcontent';
  $quicktabs['tabs'] = $tabs;
  $quicktabs['style'] = 'Zen';
	// Change to TRUE if I can get the JS to load properly.
  $quicktabs['ajax'] = FALSE;
  return $quicktabs;
}

function youth_training_content_uywi() {
 $content = '';
 
 $uywi_videos = quicktabs_load(20);
 $uywi_videos_rendered = theme('quicktabs', $uywi_videos);
 $uywi_general_sessions = quicktabs_load(8);
 $uywi_general_sessions_rendered = theme('quicktabs', $uywi_general_sessions);
 $uywi_workshops = quicktabs_load(9);
 $uywi_workshops_rendered = theme('quicktabs', $uywi_workshops);
 
 $content .= '<div id="ytc-uywi-videos" class="ytc-section"><h2>Videos</h2>';
 $content .= $uywi_videos_rendered . '</div><div class="clearer"></div>';
 $content .= '<div id="ytc-uywi-general-sessions" class="ytc-section"><h2>General Sessions</h2>';
 $content .= $uywi_general_sessions_rendered . '</div><div class="clearer"></div>';
 $content .= '<div id="ytc-uywi-workshops" class="ytc-section"><h2>Workshops</h2>';
 $content .= $uywi_workshops_rendered . '</div><div class="clearer"></div>';
 return $content;
}

function youth_training_content_ccda() {
 
 $ccda_general_sessions = quicktabs_load(18);
 $ccda_general_sessions_rendered = theme('quicktabs', $ccda_general_sessions);
 $ccda_workshops = quicktabs_load(19);
 $ccda_workshops_rendered = theme('quicktabs', $ccda_workshops);
 
 $content .= '<div id="ytc-ccda-general-sessions" class="ytc-section"><h2>General Sessions</h2>';
 $content .= $ccda_general_sessions_rendered . '</div><div class="clearer"></div>';
 $content .= '<div id="ytc-ccda-workshops" class="ytc-section"><h2>Workshops</h2>';
 $content .= $ccda_workshops_rendered . '</div><div class="clearer"></div>';
 return $content;
}