<?php
// $Id$

/** 
* Implements hook_help()
 */
function youth_training_content_help($path, $arg) {
  $output = '';
  switch($path) {
    case 'admin/help#youth_training_content':
      $output = '<p>' . t('Creates a Quicktabs block programmatically for the All Youth Training Content panel.') . '</p>';
      break;
  }
  return $output;
}

/**
 * Implements hook_menu().
 */
function youth_training_content_menu() {
  $items = array();

  $items['youth'] = array(
    'title' => 'Urban Youth Ministry Training Library',
    'page callback' => 'youth_training_content_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['youth/embed'] = array(
    'title' => 'Embed the Urban Youth Ministry Training Library',
    'page callback' => 'youth_training_content_embed_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );  
  return $items;
}

/**
 * Page/block callback for /youth.
 * Shows all youth training content (in Quicktabs).
 */
function youth_training_content_page() {
  $output = '';
  $output .= '<div id="ytc-embed-form">' . drupal_get_form('ytc_embed_code_form') . '</div>';
  $output .= theme('quicktabs', youth_training_content_quicktabs());
  return $output;
}

/**
 * Page callback for the /youth embed code.
 */
function youth_training_content_embed_page() {
  $output = '';
  $output .= '<p>To embed the entire <a href="/youth">youth training library</a> on your site,  you may use the following code:</p>';
  $output .= drupal_get_form('ytc_embed_code_form');
  return $output;
}

/**
 * Form definition for the embed code page.
*/
function ytc_embed_code_form() {
  $code = ytc_get_embed_code();

  $form = array();
  $form['ytc_embed_code'] = array(
    '#type' => 'fieldset', 
    '#title' => t('Embed this page'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['ytc_embed_code']['code'] = array(
    '#type' => 'textarea',
    '#title' => t('Embed code'),
    '#description' => t('Copy and paste this code into the &lt;body&gt; of your website\'s HTML'),
    '#value' => $code,
    '#maxlength' => FALSE,
  );
  return $form;
}

/**
 * Generates the embed code itself.
*/
function ytc_get_embed_code() {
  $embed_code = <<<EOF
<!-- begin TechMission UrbanMinistry.org embed code for youth ministry library -->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript">
$(function(){  
  var if_height,  
    src = 'http://www.urbanministry.org/remote-block/html/youth_training_content/ytc_quicktab#' + encodeURIComponent( document.location.href ),    
    iframe = $( '<iframe " src="' + src + '" width="600" height="500" scrolling="yes" frameborder="0"><\/iframe>' )
      .appendTo( '#iframe' ); 
});
</script>
<div id="iframe"></div>
<!-- end embed code -->
EOF;
  return $embed_code;
}

/**
 * Implements hook_block().
 */
function youth_training_content_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks['ytc_quicktab'] = array(
      'info' => t('Youth Training Content'),
      'weight' => 0, 
      'status' => 0, 
      'cache' => BLOCK_NO_CACHE,
    );
    $blocks['ytc_toolkit'] = array(
      'info' => t('Youth Training Content: Toolkit'),
      'weight' => 0, 
      'status' => 0, 
      'cache' => BLOCK_NO_CACHE,
    );
    $blocks['ytc_uywi'] = array(
      'info' => t('Youth Training Content: UYWI'),
      'weight' => 0, 
      'status' => 0, 
      'cache' => BLOCK_NO_CACHE,
    );
    $blocks['ytc_ccda'] = array(
      'info' => t('Youth Training Content: CCDA'),
      'weight' => 0, 
      'status' => 0, 
      'cache' => BLOCK_NO_CACHE,
    );
    $blocks['ytc_encyclopedia'] = array(
      'info' => t('Youth Training Content: Encyclopedia'),
      'weight' => 0, 
      'status' => 0, 
      'cache' => BLOCK_NO_CACHE,
    );
    return $blocks;
  }
  elseif ($op == 'view') {
    switch($delta) {
      case 'ytc_quicktab':
        $block = array(
          'subject' => t('Urban Youth Ministry Training Library'),
          'content' => youth_training_content_page(),
        );
        break;
      case 'ytc_toolkit':
        $block = array(
         'content' => youth_training_content_toolkit(),
        );
        break;
      case 'ytc_uywi':
        $block = array(
         'content' => youth_training_content_uywi(),
        );
        break;
      case 'ytc_ccda':
        $block = array(
         'content' => youth_training_content_ccda(),
        );
        break;
      case 'ytc_encyclopedia':
        $block = array(
         'content' => youth_training_content_wiki(),
        );
        break;
    }
    return $block;
  }
}

/**
 * Quicktabs block for the /youth-training-content page.
 * Returns a quicktabs array with all youth training content.
 */
function youth_training_content_quicktabs() {
  // Initialize an empty tabs array for the Quicktabs.
  $tabs = array();
  // Add the Toolkit tab (all resources from sites).
  $tabs[] = array(
    'bid' => 'youth_training_content_delta_ytc_toolkit',
    'hide_title' => TRUE,
    'title' => 'Toolkit',
    'weight' => -100,
    'type' => 'block',
  );
  // Add the UYWI tab.
  // This, and the other tabs must be defined as custom blocks or else they could not use AJAX.
  $tabs[] = array(
    'bid' => 'youth_training_content_delta_ytc_uywi',
    'hide_title' => TRUE,
    'title' => 'UYWI',
    'weight' => -80,
    'type' => 'block',
  );
  // Add the CCDA tab.
  $tabs[] = array(
    'bid' => 'youth_training_content_delta_ytc_ccda',
    'hide_title' => TRUE,
    'title' => 'CCDA',
    'weight' => -60,
    'type' => 'block',
  );
  // Add the FASTEN tab.
  $tabs[] = array(
    'nid' => 9767,
    'title' => 'FASTEN',
    'weight' => -100,
    'type' => 'node',
  );
  // Add the Urban Youth Ministry Encyclopedia tab.
  $tabs[] = array(
    'bid' => 'youth_training_content_delta_ytc_encyclopedia',
    'hide_title' => TRUE,
    'title' => 'Youth Encyclopedia',
    'weight' => -20,
    'type' => 'block',
  );
  $quicktabs['qtid'] = 'youthtrainingcontent';
  $quicktabs['tabs'] = $tabs;
  $quicktabs['style'] = 'Zen';
  // Change to TRUE if I can get the JS to load properly.
  $quicktabs['ajax'] = FALSE;
  return $quicktabs;
}

function youth_training_content_toolkit() {
  $content = '';

  $toolkit = quicktabs_load(21);
  $toolkit_rendered = theme('quicktabs', $toolkit);
  $content .= '<div id="ytc-toolkit" class="ytc-section">' . $toolkit_rendered . '</div>';
  return $content;
}
  
function youth_training_content_uywi() {
  $content = '';

  $uywi_videos = quicktabs_load(20);
  $uywi_videos_rendered = theme('quicktabs', $uywi_videos);
  $uywi_general_sessions = quicktabs_load(8);
  $uywi_general_sessions_rendered = theme('quicktabs', $uywi_general_sessions);
  $uywi_workshops = quicktabs_load(9);
  $uywi_workshops_rendered = theme('quicktabs', $uywi_workshops);

  $content .= '<div id="ytc-uywi-videos" class="ytc-section"><h2>Videos</h2>';
  $content .= $uywi_videos_rendered . '</div><div class="clearer"></div>';
  $content .= '<div id="ytc-uywi-general-sessions" class="ytc-section"><h2>General Sessions</h2>';
  $content .= $uywi_general_sessions_rendered . '</div><div class="clearer"></div>';
  $content .= '<div id="ytc-uywi-workshops" class="ytc-section"><h2>Workshops</h2>';
  $content .= $uywi_workshops_rendered . '</div><div class="clearer"></div>';
  return $content;
}

function youth_training_content_ccda() {

  $ccda_general_sessions = quicktabs_load(18);
  $ccda_general_sessions_rendered = theme('quicktabs', $ccda_general_sessions);
  $ccda_workshops = quicktabs_load(19);
  $ccda_workshops_rendered = theme('quicktabs', $ccda_workshops);

  $content .= '<div id="ytc-ccda-general-sessions" class="ytc-section"><h2>General Sessions</h2>';
  $content .= $ccda_general_sessions_rendered . '</div><div class="clearer"></div>';
  $content .= '<div id="ytc-ccda-workshops" class="ytc-section"><h2>Workshops</h2>';
  $content .= $ccda_workshops_rendered . '</div><div class="clearer"></div>';
  return $content;
}

function youth_training_content_wiki() {
  $content = '';

  $wiki = quicktabs_load(10);
  $wiki_rendered = theme('quicktabs', $wiki);
  $content .= '<div id="ytc-wiki" class="ytc-section">' . $wiki_rendered . '</div>';
  return $content;
}